### PR TITLE
Add NOTICE

### PR DESCRIPTION
**Pull request by cartermp**

### CODE REVIEW

**Review by JamieDanielson — COMMENTED** [review]
This one has a different license, does that change the NOTICE?

**Comment by cartermp** [comment]
Yes, absolutely. Will update here

**Comment by cartermp** [comment]
Actually, let's hold on this one as well. I think we could just close this PR, but we can bring it up.

**Comment by bdarfler** [comment]
@cartermp I think we will want to update the content of the notice to be this

https://github.com/honeycombio/atlas/blob/main/LICENSE#L635-L648

**Comment by cartermp** [comment]
Okay, this one should be ready now.

**Review by MikeGoldsmith — APPROVED** [review]

**Pull request merged**
